# Generated by Django 5.0.6 on 2024-07-22 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0014_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
    ]
