# Generated by Django 5.1 on 2024-09-04 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0016_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
    ]
