# Generated by Django 5.1 on 2024-09-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0017_remove_user_code_remove_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, max_length=20, verbose_name='code'),
        ),
    ]
