# Generated by Django 5.1 on 2024-10-30 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0019_user_role_doctorprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.DeleteModel(
            name='DoctorProfile',
        ),
    ]
